name: MRR_Report
description: ''
version: '0.8'
author: baibhab.patnaik@sonata-software.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: mrrreport
  parentArtefactID: baibhabpatnaiksonatasoftwarecomteam
  buildSystem: wheel
  author: null
  createdAt: '2023-11-21 06:20:27'
pipelines:
  pipelines/customer_spending:
    name: customer_spending
    description: ''
    author: baibhab.patnaik@sonata-software.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-11-21 06:33:39'
    datasets:
      inputs:
      - datasets/customer_Source
      - datasets/order_source
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/customer_Source:
    name: customer_Source
    description: ''
    author: baibhab.patnaik@sonata-software.com
    createdAt: '2023-11-21 06:40:39'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 7037
        datasetType: File
        description: ''
        author: baibhab.patnaik@sonata-software.com
        createdAt: '2023-11-21 06:40:39'
  datasets/order_source:
    name: order_source
    description: ''
    author: baibhab.patnaik@sonata-software.com
    createdAt: '2023-11-21 06:46:22'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 7037
        datasetType: File
        description: ''
        author: baibhab.patnaik@sonata-software.com
        createdAt: '2023-11-21 06:46:22'
  datasets/Reports:
    name: Reports
    description: ''
    author: baibhab.patnaik@sonata-software.com
    createdAt: '2023-11-21 07:14:41'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 7037
        datasetType: File
        description: ''
        author: baibhab.patnaik@sonata-software.com
        createdAt: '2023-11-21 07:14:41'
templates: {}
jobs:
  jobs/schedule_report:
    name: schedule_report
    description: ''
    fabricUID: 7037
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: Small
    scheduleCron: 0 56 12 * * ? *
    timeout: null
    alerting:
      emails: baibhab.patnaik@sonata-software.com
      onStart: false
      onSuccess: true
      onFailure: true
    pipelines:
    - pipelines/customer_spending
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-11-21 07:24:34'
    author: baibhab.patnaik@sonata-software.com
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
functions:
  author: null
  createdAt: '2023-11-21 06:20:27'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2023-11-21 06:19:13'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-11-21 06:19:13'
pipelineConfigurations: {}
